<a href="https://colab.research.google.com/github/0601ankitsagar/ML_LAB_2026-27/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

In [11]:
list1 =[1,2,3,4,5]
array1 = np.array(list1)
print(array1)

[1 2 3 4 5]


In [12]:
array1 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])
print(array1)

[[1 2 3 4]
 [5 6 7 8]]


In [13]:
array1 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])

print(array1)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [14]:
array1 = np.array([2, 4, 6])

print(array1.dtype)

int64


In [15]:
print(array1.ndim)

1


In [16]:
print(array1.size)

3


In [17]:
array1 = np.array([[1, 2, 3],
                [6, 7, 8]])

print(array1.shape)

(2, 3)
