<a href="https://colab.research.google.com/github/0601ankitsagar/ML_LAB_2026-27/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

In [11]:
list1 =[1,2,3,4,5]
array1 = np.array(list1)
print(array1)

[1 2 3 4 5]


In [12]:
array1 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])
print(array1)

[[1 2 3 4]
 [5 6 7 8]]


In [13]:
array1 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])

print(array1)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [14]:
array1 = np.array([2, 4, 6])

print(array1.dtype)

int64


In [15]:
print(array1.ndim)

1


In [16]:
print(array1.size)

3


In [17]:
array1 = np.array([[1, 2, 3],
                [6, 7, 8]])

print(array1.shape)

(2, 3)


In [18]:
array1 = np.array([6, 7, 8, 10, 13])

array2 = np.array([6, 7, 8, 10, 13], dtype=np.int32)

print(array1.itemsize)
print(array2.itemsize)

8
4


In [19]:
array1 = np.array([6, 7, 8])
array2 = np.array([[1, 2, 3],
                   	    [6, 7, 8]])

print("\nData of array1 is: ",array1.data)
print("Data of array2 is: ",array2.data)


Data of array1 is:  <memory at 0x7fd553ee8a00>
Data of array2 is:  <memory at 0x7fd553f25150>


In [ ]:
array1 = np.array([1, 3, 5, 7, 9])

print(array1[0])
print(array1[2])
print(array1[4])

In [ ]:
array1[1]=10
print(array1)

In [20]:
array1 = np.array([[1, 3, 5, 7],
                       [9, 11, 13, 15],
                       [2, 4, 6, 8]])

element1 = array1[1, 3]
print("4th Element at 2nd Row:",element1)

element2 = array1[0, 1]  # returns 3
print("2nd Element at First Row:",element2)

4th Element at 2nd Row: 15
2nd Element at First Row: 3
